name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Dump checkout result
        run: |
          pwd
          ls
      - name: Deploy
        run: |
          yarn install
          yarn run deploy
