name: Build Vue
on: push

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Dump checkout result
        run: |
          pwd
          ls
      - name: Deploy
        run: |
          echo "$PUSHER_NAME"
          echo "$PUSHER_EMAIL"
          git config --global user.name "$PUSHER_NAME"
          git config --global user.email "$PUSHER_EMAIL"
          yarn install
          yarn run deploy
