name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Dump checkout result
        run: |
          pwd
          ls
      - name: Vue to Github Pages with yarn
        uses: hotrungnhan/VuePagesAction@1.0.1
        with:
          username: "SangheonYi"
          reponame: "VueTuto"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
