name: Build Vue
on: merge

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2

      - name: Dump checkout result
        run: |
          pwd
          ls
      - name: Deploy
        env:
          PUSHER_NAME: ${{ github.event.pusher.name }}
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
          REPOSITORY: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name "$PUSHER_NAME"
          git config --global user.email "$PUSHER_EMAIL"
          yarn install
          yarn run build
          cd dist
          git init
          git add -A
          git commit -m 'deploy: Deploy from CD'
          git push -f "https://$PUSHER_NAME:$ACCESS_TOKEN@github.com/$REPOSITORY.git" master:gh-pages
